### ISSUE TITLE
Output to file instead of folder

### ISSUE THREAD

**Issue by slinnarsson** [linnarsson-lab/BackSPIN#1]
Since the output is a single CEF file, it would be better to just write that file directly (and not put it inside a run folder).

**Comment by gioelelm** [comment]
Ok so we provide just this output for now?

**Comment by slinnarsson** [comment]
What else did you have in mind?

**Comment by gioelelm** [comment]
plots, correlation matrix, other formats? ...maybe is unnecessary though.
Ok I will make the change. How do I update it on github?

**Comment by slinnarsson** [comment]
You need git. See http://rogerdudler.github.io/git-guide/

Then:

git clone https://github.com/linnarsson-lab/BackSPIN

Make changes locally on your laptop

git add <filename>
git commit -m "Made some changes"
git push

**Comment by slinnarsson** [comment]
Might be a good idea to make a separate tool for visualizing a CEF file. Correlation matrix, barplots, histograms - then it could be used on any CEF i.e. one clustered by other methods.

**Comment by gioelelm** [comment]
Sure, with matplotlib is quite straightforward. Even interactive heat map like the one I am used to work with could be useful.
