### ISSUE TITLE
SPIN mode fails when axisvalue != 'both'

### ISSUE THREAD

**Issue by sformic** [linnarsson-lab/BackSPIN#4]
Hello,
I tried to run BackSPIN in the SPIN mode (bash command: python backSPIN.py -i oligos.cef -o prova_out.cef -b 1 -t 10 -f 500 -d 4 -v) but it gave me the following error:
"Traceback (most recent call last):
  File "backSPIN.py", line 881, in <module>
    results = SPIN(dt, widlist=runs_step, iters=runs_iters, axis=normal_spin_axis, verbose=verbose)
NameError: name 'dt' is not defined"

Thus I modified the variable 'dt' in'data' from line 881 until the end of the file. The result was not having the original error message anymore, but instead a different error regarding the type of 'axis' variable, so I tried to fix it modifying some lines and all my modifications are at the branch https://github.com/sformic/BackSPIN/commit/7f61138373e073f16139708120a3240d548ff09f. 
After my modifications the normal SPIN mode seems working when axisvalue = 'both', but with axisvalue = (0|1) it gives me the following error:
"Traceback (most recent call last):
  File "backSPIN.py", line 910, in <module>
    output_cef.set_matrix(data[results[0],:][:,results[1]])
IndexError: too many indices"

I don't manage to fix this last error and I also don't want to change more the code. I'm already not sure that after my modifications the script is working as expected and giving me the correct result. For these two reasons I would like a feedback in order to use BackSPIN in the SPIN mode properly.

Thank you in advance

sformic

**Comment by gioelelm** [comment]
Sorry for the delay. Bug is now fixed by my latest commit 33285f0fcb80754890131fc29cdb37f287259baa.
For now this is fixed only to the .py source code and a fixed packaged binary will be available soon @slinnarsson
